spring:
  application:
    name: local
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

# debug: true
logging:
  level:
    org.springframework.boot.autoconfigure: ERROR
#    org.springframework.web: DEBUG
