
spring:
  profiles:
    include: secret
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

#server:
#  port: 8081
#      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
# debug: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.web: DEBUG


jwt:
  secret : ${MY_JWT_KEY}
  access-token:
    expiration : ${ACCESS_TOKEN_DURATION}
  refresh-token:
    expiration: ${REFRESH_TOKEN_DURATION}